<?php

namespace AppBundle\Repository;

/**
 * AfectadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfectadoRepository extends \Doctrine\ORM\EntityRepository
{
}
