<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CodConclusion;

/**
 * CodConclusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodConclusionRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarConclusion($data)
    {
        try{
            $em = $this->getEntityManager();
            $conclusion = new CodConclusion();
            $conclusion->setNombre(strtoupper($data['nombre']));

            $em->persist($conclusion);
            $em->flush();
            $msg = $conclusion;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La conclusión ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la conclusión';
            }
        }

        return $msg;
    }

    public function modificarConclusion($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $conclusion = $em->getRepository('AppBundle:CodConclusion')->find($data['idConclusion']);
            $conclusion->setNombre(strtoupper($data['nombre']));

            $em->persist($conclusion);
            $em->flush();
            $msg = $conclusion;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'Existe una conclusión con este nombre  , no se puede hacer esta modificación';
            }
            else
            {
                $msg = 'Se produjo un error al modificar la conclusión';
            }
        }

        return $msg;
    }

    public function eliminarConclusion($id)
    {
        try {
            $em = $this->getEntityManager();
            $conclusion = $em->getRepository('AppBundle:Codconclusion')->find($id);

            $em->remove($conclusion);
            $em->flush();
            $msg = $conclusion;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen datos asociados a esta conclusión , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la conclusión';
            }
        }
        return $msg;
    }

}
