<?php

namespace AppBundle\Repository;

/**
 * CodClasificacionReclamacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodClasificacionReclamacionRepository extends \Doctrine\ORM\EntityRepository
{
}
