<?php

namespace AppBundle\Repository;

/**
 * CodConformidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodConformidadRepository extends \Doctrine\ORM\EntityRepository
{
}
