<?php

namespace AppBundle\Repository;

/**
 * CodEstadoReclamacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodEstadoReclamacionRepository extends \Doctrine\ORM\EntityRepository
{
}
