<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CodPais;

/**
 * CodPaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodPaisRepository extends \Doctrine\ORM\EntityRepository
{
    public function  agregarPais($data)
    {
        try{
            $em = $this->getEntityManager();
            $pais = new CodPais();
            $pais->setCodigo($data['codigo']);
            $pais->setNombre($data['nombre']);

            $em->persist($pais);
            $em->flush();
            $msg = $pais;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El país ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el país';
            }
        }

        return $msg;
    }

    public function modificarPais($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $pais = $em->getRepository('AppBundle:CodPais')->find($data['idPais']);
            $pais->setCodigo($data['codigo']);
            $pais->setNombre($data['nombre']);

            $em->persist($pais);
            $em->flush();
            $msg = $pais;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'Existe un país con este código  , no se puede hacer esta modificación';
            }
            else
            {
                $msg = 'Se produjo un error al modificar el País';
            }
        }

        return $msg;
    }

    public function eliminarPais($id)
    {
        try
        {
            $em = $this->getEntityManager();
            $pais = $em->getRepository('AppBundle:CodPais')->find($id);

            $em->remove($pais);
            $em->flush();
            $msg = $pais;

        }catch (\Exception $e){

            if(strpos($e->getMessage() , 'foreign key') > 0)
            {
                $msg = 'Existen datos asociados a este país , no se puede eliminar';
            }
            else
            {
                $msg = 'Se produjo un error al eliminar el país';
            }
        }
        return $msg;
    }

}
