<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CodProvincia;

/**
 * CodProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodProvinciaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarProvincia($data)
    {
        try{
            $em = $this->getEntityManager();
            $provincia = new CodProvincia();
            $provincia->setCodigo(strtoupper($data['codigo']));
            $provincia->setNombre(strtoupper($data['nombre']));

            $em->persist($provincia);
            $em->flush();
            $msg = $provincia;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La provincia ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la provincia';
            }
        }

        return $msg;
    }

    public function modificarProvincia($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $provincia = $em->getRepository('AppBundle:CodProvincia')->find($data['idProvincia']);
            $provincia->setCodigo(strtoupper($data['codigo']));
            $provincia->setNombre(strtoupper($data['nombre']));

            $em->persist($provincia);
            $em->flush();
            $msg = $provincia;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'Existe una provincia con este código  , no se puede hacer esta modificación';
            }
            else
            {
                $msg = 'Se produjo un error al modificar la provincia';
            }
        }

        return $msg;
    }

    public function eliminarProvincia($id)
    {
        try {
            $em = $this->getEntityManager();
            $provincia = $em->getRepository('AppBundle:CodProvincia')->find($id);

            $em->remove($provincia);
            $em->flush();
            $msg = $provincia;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen datos asociados a esta provincia , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la provincia';
            }
        }
        return $msg;
    }

}
