<?php

namespace AppBundle\Repository;

/**
 * CodProcedenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodProcedenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
