<?php

namespace AppBundle\Repository;

/**
 * PromoventeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoventeRepository extends \Doctrine\ORM\EntityRepository
{
}
