<?php

namespace AppBundle\Repository;

/**
 * ReclamacionUnidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamacionUnidadRepository extends \Doctrine\ORM\EntityRepository
{
}
