<?php

namespace AppBundle\Repository;

/**
 * ReclamacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamacionRepository extends \Doctrine\ORM\EntityRepository
{
}
